= Download and Install Anypoint Studio 7.2 (Windows)

To install Anypoint Studio 7.2:

. Download Anypoint Studio from the link:https://www.mulesoft.com/lp/dl/studio[Anypoint Studio Download Site].
. If prompted, follow the prompts to install the JDK 8 for your operating system.
+
[NOTE]
--
You may get a Windows firewall warning if this is the first time JDK has been installed to your computer. We recommend that you allow access to enable all functions of Anypoint Studio. If you do not allow access, some features of Anypoint Studio may not work properly.

If you get a Windows warning about running executable files (EXE) downloaded from the internet, verify that the publisher is MuleSoft. Click Yes to proceed.
--

. Accept the license agreement.
. Select the installation location. 
. Open the installed Anypoint Studio.
. Click OK to accept the default workspace. +
+
[NOTE]
--
Do not reuse a workspace used by Anypoint Studio 6.x or below. +
If you choose to use an existing workspace, this must have been created using Anypoint Studio 7.0 or above.
--



== See Also

* link:/anypoint-studio/v/7.2/studio-xulrunner-wx-task[To Configure XULRunner as Studio's Default Layout Engine (Windows)]
* link:/anypoint-studio/v/7.2/jdk-requirement-wx-workflow[To Configure Java JDK (Windows)]
* link:/anypoint-studio/v/7.2/studio-configure-vm-task-wx[To Configure Studio's Default VM (Windows)]
